import Sidebar from "@/components/Sidebar";
import "@/styles/globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">

          <div className="bg-gray-700/50 max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
            <Sidebar />
          </div>

          <div className="flex-1">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
